lib/bebemayotte_web/router.ex
defmodule BebemayotteWeb.Router do
  use BebemayotteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BebemayotteWeb do
    pipe_through :browser

      # PAGE CONTROLLER
    get "/", PageController, :index

      # SEARCH
    post "/search", PageController, :search

      # SESSION
    get "/connexion", PageController, :connexion
    post "/connexions", PageController, :submit_connexion
    get "/inscription", PageController, :inscription
    post "/inscriptions", PageController, :submit_inscription

      # CLIENT REACTION
    get "/contact", PageController, :contact
    post "/send_message", PageController, :send_message_contact
    get "/question", PageController, :question

    # PANIER
    get "/panier", PageController, :panier
    get "/add-panier", PageController, :add_panier
    get "/delete-panier", PageController, :delete_panier
    post "/update-panier", PageController, :update_panier


      # PRODUIT
    get "/produit", PageController, :produit
    get "/produit/:cat", PageController, :produit_categorie
    get "/produit/:cat/:souscat", PageController, :produit_souscategorie
    get "/show_produit/:id", PageController, :detail_produit

      # COMPTE CONTROLLER
    get "/account", CompteController, :compte
    get "/commandes", CompteController, :commandes
    get "/download", CompteController, :down
    get "/adresse", CompteController, :adresse
    get "/detail", CompteController, :detail
    post "/update-account", CompteController, :update_account
    delete "/deconnexion", CompteController, :deconnexion
    get "/update_address/facturation", CompteController, :update_facturation
    post "/update_address/facturation/submit", CompteController, :submit_update_facturation
    get "/update_address/livraison", CompteController, :update_livraison
    post "/update_address/livraison/submit", CompteController, :submit_update_livraison

      # COMMAND
    get "/see_command", CompteController, :see_command
    get "/pay_command", CompteController, :pay_command
    get "/politique", CompteController, :politique

      # FORGET PASSWORD
    get "/ask_email", CompteController, :ask_email

  end

  # Other scopes may use custom stacks.
  # scope "/api", BebemayotteWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser
  #   end
  # end
end

lib/bebemayotte_web/controllers/compte_controller.ex
defmodule BebemayotteWeb.CompteController do
  use BebemayotteWeb, :controller
  alias Bebemayotte.CatRequette
  alias Bebemayotte.UserRequette

  # GET PRINCIPAL PAGE
  def compte(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"compte.html", user: user, categories: categories, search: nil)
    end
  end

  # GET COMMAND PAGE
  def commandes(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"commandes.html", user: user, categories: categories, search: nil)
    end
  end

  # GET DOWNLOAD PAGE
  def down(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"down.html", user: user, categories: categories, search: nil)
    end
  end

  # GET DETAIL PAGE
  def detail(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"detail.html", categories: categories, user: user, search: nil)
    end
  end

  # GET ADDRESS PAGE
  def adresse(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"adresse.html", user: user, categories: categories, search: nil)
    end
  end

  # FUNCTION
  defp for_update(char, new_c, bd_c, u) do
    if new_c != "" and new_c != bd_c do
      params = %{
        "#{char}" => new_c
      }
      UserRequette.update_user_query(u, params)
    end
  end

  # UPDATE COMPTE
  def update_account(conn, %{
    "prenom" => prenom,
    "nom" => nom,
    "nom_affiche" => nom_affiche,
    "adresseMessage" => adresseMessage,
    "motdepasse_actuel" => motdepasse_actuel,
    "motdepasse_new" => motdepasse_new,
    "motdepasse_new_confirm" => motdepasse_new_confirm
  }) do

    id = Plug.Conn.get_session(conn, :user_id)
    user = UserRequette.get_user_by_id(id)

    for_update("prenom", prenom, user.prenom, user)
    for_update("nom", nom, user.nom, user)
    for_update("nom_affiche", nom_affiche, user.nom_affiche, user)
    for_update("adresseMessage", adresseMessage, user.adresseMessage, user)

    if motdepasse_actuel != user.motdepasse do
      conn
        |>put_flash(:mdp_error, "Mot de passe éronné!")
        |>redirect(to: "/detail")
    else
      if motdepasse_new == user.motdepasse do
        conn
          |>put_flash(:mdp_error, "Mot de passe semblable à l'ancien!")
          |>redirect(to: "/detail")
      else
        if motdepasse_new != motdepasse_new_confirm do
          conn
            |>put_flash(:mdp_error, "Mot de passe non confirmé, le nouveau!")
            |>redirect(to: "/detail")
        else
          params = %{
            "motdepasse" => motdepasse_new
          }
          UserRequette.update_user_query(user, params)
        end
      end
    end

    conn
      |>put_flash(:info_update, "Mise à jour réussi!")
      |>redirect(to: "/detail")
  end

  # DECONNEXION
  def deconnexion(conn, %{"hidden" => hidden}) do
    IO.puts hidden
    conn
      |>configure_session(drop: true)
      |>redirect(to: "/connexion")
  end

  #------------------------------------------------------------------------------COMMAND-----------------------------------------------------------------------------------

  # SEE MY COMMAND
  def see_command(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"voir.html", user: user, categories: categories, search: nil)
    end
  end

  # PAY COMMAND
  def pay_command(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"payer.html", user: user, categories: categories, search: nil)
    end
  end

  # CONFIDENTIALITY POLITIC
  def politique(conn,_params) do
    categories = CatRequette.get_all_categorie()

    render(conn,"politique.html", categories: categories, search: nil)
  end

  # GET PAGE FACTURATION
  def update_facturation(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"modifier.html", user: user, categories: categories, search: nil)
    end
  end

  # SUBMIT "UPDATE FACTURATION"
  def submit_update_facturation(conn, %{
    "prenom" => prenom,
    "nom" => nom,
    "nom_entreprise" => nom_entreprise,
    "nom_rue" => nom_rue,
    "batiment" => batiment,
    "ville" => ville,
    "codepostal" => codepostal,
    "telephone" => telephone,
    "adresseMessage" => adresseMessage
  }) do
    id = Plug.Conn.get_session(conn, :user_id)
    user = UserRequette.get_user_by_id(id)
    tel = Integer.to_string(telephone)

    for_update("prenom", prenom, user.prenom, user)
    for_update("nom", nom, user.nom, user)
    for_update("nom_entreprise", nom_entreprise, user.nom_entreprise, user)
    for_update("nom_rue", nom_rue, user.nom_rue, user)
    for_update("batiment", batiment, user.batiment, user)
    for_update("ville", ville, user.ville, user)
    for_update("codepostal", codepostal, user.codepostal, user)
    for_update("telephone", tel, user.telephone, user)
    for_update("adresseMessage", adresseMessage, user.adresseMessage, user)

    conn
      |>put_flash(:info_update, "Mise à jour réussi!")
      |>redirect(to: "/update_address/facturation")
  end

  # GET PAGE LIVRAISON
  def update_livraison(conn,_params) do
    id = Plug.Conn.get_session(conn, :user_id)
    categories = CatRequette.get_all_categorie()

    if is_nil(id) do
      redirect(conn, to: "/connexion")
    else
      user = UserRequette.get_user_by_id(id)
      render(conn,"modification.html", user: user, categories: categories, search: nil)
    end
  end

  # SUBMIT "UPDATE FACTURATION"
  def submit_update_livraison(conn, %{
    "prenom" => prenom,
    "nom" => nom,
    "nom_entreprise" => nom_entreprise,
    "nom_rue" => nom_rue,
    "batiment" => batiment,
    "ville" => ville,
    "codepostal" => codepostal
  }) do
    id = Plug.Conn.get_session(conn, :user_id)
    user = UserRequette.get_user_by_id(id)

    for_update("prenom", prenom, user.prenom, user)
    for_update("nom", nom, user.nom, user)
    for_update("nom_entreprise", nom_entreprise, user.nom_entreprise, user)
    for_update("nom_rue", nom_rue, user.nom_rue, user)
    for_update("batiment", batiment, user.batiment, user)
    for_update("ville", ville, user.ville, user)
    for_update("codepostal", codepostal, user.codepostal, user)

    conn
      |>put_flash(:info_update, "Mise à jour réussi!")
      |>redirect(to: "/update_address/livraison")
  end

  # ASK EMAIL OR IDENTIFIANT
  def ask_email(conn,_params) do
    categories = CatRequette.get_all_categorie()

    render(conn,"ask_email.html", categories: categories, search: nil)
  end

end

lib/bebemayotte_web/views/compte_view.ex
defmodule BebemayotteWeb.CompteView do
  use BebemayotteWeb, :view
end

lib/bebemayotte_web/templates/compte/adresse.html.eex
<div class="product">
	<div class="compte">
		<div class="containe">
			<nav>
				<ul class="mcd-menu">
					<li>
						<a href="/account" class="active">
							<strong>Tableau de bord</strong>
						</a>
					</li>
					<li>
						<a href="/commandes" class="active">
							<strong>Commandes</strong>
						</a>
					</li>
					<li>
						<a href="/download"class="active">
							<strong>Téléchargement</strong>
						</a>
					</li>
					<li>
						<a href="/adresse"class="active" id="active">
							<strong>Adresse</strong>				
						</a>
					</li>
					<li>
						<a href="/detail"class="active">
							<strong>Détail du compte</strong>				
						</a>
					</li>
					<li>
						<%= form_for @conn, Routes.compte_path(@conn, :deconnexion), [method: :delete], fn f -> %>
                            <%= hidden_input f, :hidden %>
							<%= submit "Déconnexion", class: "btn" %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
		<div class="contenue-compte">
			<div class="contenue-compte">
                <h3>Les adresses suivantes seront utilisées par défaut sur la page de commande.</h3>
                <div class="center">
                    <div>
                        <h2>Adresse de facturation</h2>
                        <div class="row">
                            <div class="column">
                                <p><%= @user.nom %> <%= @user.prenom %><br>
								<%= if @user.nom_rue != "null" do %>
									Rue <%= @user.nom_rue %>
								<% end %>
								 <br>
                                <%= @user.ville %> <br>
                                <%= @user.codepostal %> <br></p>
                            </div>
                            <div class="column">
                                <a href="/update_address/facturation" class="link">Modifier</a>
                            </div>
                        </div>
                    </div>
                    <div>
                        <h2>Adresse de livraison</h2>
                        <div class="row">
                            <div class="column">
                                <p><%= @user.nom %> <%= @user.prenom %><br>
								<%= if @user.nom_rue != "null" do %>
									Rue <%= @user.nom_rue %>
								<% end %>
								 <br>
                                <%= @user.ville %> <br>
                                <%= @user.codepostal %> <br></p>
                            </div>
                            <div class="column">
                                <a href="/update_address/livraison" class="link">Modifier</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
	    </div>
	</div>
</div>

lib/bebemayotte_web/templates/compte/ask_email.html.eex
<div class="product">
    <div class="motdepasse">
        <h1 id="title">Mon Compte</h1>
        <p>Mot de passe perdu ? Veuillez saisir votre identifiant ou votre adresse e-mail.<br> 
        Vous recevrez un lien par e-mail pour créer un nouveau mot de passe.</p>
        <div class="detail">
            <label>Identifiant ou e-mail
                <input type="text">
            </label>
        </div>
        <div id="btn">
        <button class="btn">Réinitialisation du mot de passe</button>
    </div>
    </div>
</div>

lib/bebemayotte_web/templates/compte/commandes.html.eex
<div class="product">
	<div class="compte">
		<div class="containe">
			<nav>
				<ul class="mcd-menu">
					<li>
						<a href="/account" class="active">
							<strong>Tableau de bord</strong>
						</a>
					</li>
					<li>
						<a href="/commandes" class="active" id="active">
							<strong>Commandes</strong>
						</a>
					</li>
					<li>
						<a href="/download"class="active">
							<strong>Téléchargement</strong>
						</a>
					</li>
					<li>
						<a href="/adresse"class="active">
							<strong>Adresse</strong>				
						</a>
					</li>
					<li>
						<a href="/detail"class="active">
							<strong>Détail du compte</strong>				
						</a>
					</li>
					<li>
						<%= form_for @conn, Routes.compte_path(@conn, :deconnexion), [method: :delete], fn f -> %>
							<%= hidden_input f, :hidden %>
							<%= submit "Déconnexion", class: "btn" %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
		<div class="contenue-compte">
            <div class="vide">
                <img src="<%= Routes.static_path(@conn, "/images/online-shop.png") %>"> <h3>Aucune commande n’a encore été passée.</h3>
            </div>
            <div class="bouton-retour">
                <button type="submit" class="retour">
                    Parcourir les produits
                </button>
            </div>		
		</div>
	</div>
</div>











































 

lib/bebemayotte_web/templates/compte/compte.html.eex
<div class="product">
	<div class="compte">
		<div class="containe">
			<nav>
				<ul class="mcd-menu">
					<li>
						<a href="/account" class="active" id="active">
							<strong>Tableau de bord</strong>
						</a>
					</li>
					<li>
						<a href="/commandes" class="active">
							<strong>Commandes</strong>
						</a>
					</li>
					<li>
						<a href="/download"class="active">
							<strong>Téléchargement</strong>
						</a>
					</li>
					<li>
						<a href="/adresse"class="active">
							<strong>Adresse</strong>				
						</a>
					</li>
					<li>
						<a href="/detail"class="active">
							<strong>Détail du compte</strong>				
						</a>
					</li>
					<li>
						<%= form_for @conn, Routes.compte_path(@conn, :deconnexion), [method: :delete], fn f -> %>
							<%= hidden_input f, :hidden %>
							<%= submit "Déconnexion", class: "btn" %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
		<div class="contenue-compte">
			<h2>Bonjour</h2>
			<p>À partir du <a class="link" href="/account">tableau de bord</a> de votre compte, vous pouvez visualiser vos <a class="link" href="/commandes">commandes <br> récentes</a>, gérer vos 
			<a class="link" href="/adresse">adresses de livraison et de facturation</a> ainsi que <a class="link" href="/detail">changer <br>
			votre mot de passe et les détails de votre compte</a> .<p>
		</div>
	</div>
</div>

lib/bebemayotte_web/templates/compte/detail.html.eex
<div class="product">
	<div class="compte">
		<div class="containe">
			<nav>
				<ul class="mcd-menu">
					<li>
						<a href="/account" class="active">
							<strong>Tableau de bord</strong>
						</a>
					</li>
					<li>
						<a href="/commandes" class="active">
							<strong>Commandes</strong>
						</a>
					</li>
					<li>
						<a href="/download"class="active">
							<strong>Téléchargement</strong>
						</a>
					</li>
					<li>
						<a href="/adresse"class="active">
							<strong>Adresse</strong>				
						</a>
					</li>
					<li>
						<a href="/detail"class="active" id="active">
							<strong>Détail du compte</strong>				
						</a>
					</li>
					<li>
						<%= form_for @conn, Routes.compte_path(@conn, :deconnexion), [method: :delete], fn f -> %>
							<%= hidden_input f, :hidden %>
							<%= submit "Déconnexion", class: "btn" %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
		<%= form_for @conn, Routes.compte_path(@conn, :update_account), [method: :post], fn f -> %>
			<div class="contenue-compte">
				<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info_update) %></p>
				<div id="detail">
					<label>Prénom *
						<%= text_input f, :prenom, value: @user.prenom %>
					</label>
					<label>Nom *
						<%= text_input f, :nom, value: @user.nom %>
					</label>
				</div>
				<div class="detail">
					<label>Nom affiché *
						<%= if @user.nom_affiche == "null" do %>
							<%= text_input f, :nom_affiche %>
						<% else %>
							<%= text_input f, :nom_affiche, value: @user.nom_affiche %>
						<% end %>
					</label>
					<h5>Indique comment votre nom apparaîtra dans la section relative au compte et dans les avis</h5>
					<label>Adresse de messagerie *
						<%= email_input f, :adresseMessage, value: @user.adresseMessage %>
					</label>
					<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :mdp_error) %></p>
					<h5>Changement de mot de passe</h5>
					<label>Mot de passe actuel (laisser vide pour le conserver)
						<%= password_input f, :motdepasse_actuel, placeholder: "Entrer votre ancien mot de passe" %>
					</label>
					<label>Nouveau mot de passe (laisser vide pour conserver l’actuel)
						<%= password_input f, :motdepasse_new, placeholder: "Entrer votre nouveau mot de passe" %>
					</label>
					<label>Confirmer le nouveau mot de passe
						<%= password_input f, :motdepasse_new_confirm, placeholder: "Confirmez votre nouveau mot de passe" %>
					</label>
				</div>
				<div id="btn">
					<%= submit "Enregistrer les modifications", class: "btn" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

lib/bebemayotte_web/templates/compte/down.html.eex
<div class="product">
	<div class="compte">
		<div class="containe">
			<nav>
				<ul class="mcd-menu">
					<li>
						<a href="/account" class="active">
							<strong>Tableau de bord</strong>
						</a>
					</li>
					<li>
						<a href="/commandes" class="active">
							<strong>Commandes</strong>
						</a>
					</li>
					<li>
						<a href="/download"class="active" id="active">
							<strong>Téléchargement</strong>
						</a>
					</li>
					<li>
						<a href="/adresse"class="active">
							<strong>Adresse</strong>				
						</a>
					</li>
					<li>
						<a href="/detail"class="active">
							<strong>Détail du compte</strong>				
						</a>
					</li>
					<li>
						<%= form_for @conn, Routes.compte_path(@conn, :deconnexion), [method: :delete], fn f -> %>
							<%= hidden_input f, :hidden %>
							<%= submit "Déconnexion", class: "btn" %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
		<div class="contenue-compte">
			<div class="vide">
                <img src="<%= Routes.static_path(@conn, "/images/download.png") %>"> <h3>Aucun téléchargement actuellement disponible.</h3>
            </div>
            <div class="bouton-retour">
                <button type="submit" class="retour">
                    Parcourir les produits
                </button>
            </div>
        </div>
	</div>
</div>

lib/bebemayotte_web/templates/compte/modification.html.eex
<div class="product">
	<div class="compte">
		<div class="containe">
			<nav>
				<ul class="mcd-menu">
					<li>
						<a href="/account" class="active">
							<strong>Tableau de bord</strong>
						</a>
					</li>
					<li>
						<a href="/commandes" class="active">
							<strong>Commandes</strong>
						</a>
					</li>
					<li>
						<a href="/download"class="active">
							<strong>Téléchargement</strong>
						</a>
					</li>
					<li>
						<a href="/adresse"class="active" id="active">
							<strong>Adresse</strong>				
						</a>
					</li>
					<li>
						<a href="/detail"class="active">
							<strong>Détail du compte</strong>				
						</a>
					</li>
					<li>
						<%= form_for @conn, Routes.compte_path(@conn, :deconnexion), [method: :delete], fn f -> %>
                            <%= hidden_input f, :hidden %>
							<%= submit "Déconnexion", class: "btn" %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
		<div class="contenue-compte">
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info_update) %></p>
            <%= form_for @conn, Routes.compte_path(@conn, :submit_update_livraison), [method: :post], fn f ->  %>    
                <div id="detail">
                    <label>Prénom *
                        <%= text_input f, :prenom, value: @user.prenom %>
                    </label>
                    <label>Nom *
                        <%= text_input f, :nom, value: @user.nom %>
                    </label>
                </div>
                <div class="detail">
                    <label>Nom de l'entreprise *
                        <%= if @user.nom_entreprise == "null" do %>
                            <%= text_input f, :nom_entreprise %>
                        <% else %>
                            <%= text_input f, :nom_entreprise, value: @user.nom_entreprise %>
                        <% end %>
                    </label>
                    <label>Pays/région * </label>
                    <label><strong><%= @user.pays %><strong></label>
                    <label>Numéro et nom de rue *
                        <%= if @user.nom_rue == "null" do %>
                            <%= text_input f, :nom_rue %>
                        <% else %>
                            <%= text_input f, :nom_rue, value: @user.nom_rue %>
                        <% end %>
                        <%= if @user.nom_rue == "null" do %>
                            <%= text_input f, :batiment, placeholder: "Bâtiment, appartement, lot,etc. (facultatif)" %>
                        <% else %>
                            <%= text_input f, :batiment, value: @user.batiment %>
                        <% end %>
                    </label>
                    <label>Ville
                        <p><strong><%= @user.ville %><strong><p>
                        <%= select f, :ville, ["AJANGOUA", "BAMBO-EST", "BAMBO-OUEST", "BANDRABOUA", "BANDRéLé", "BARAKANI", "BOUYOUNI", "BOUéNI", "CHEMBENYOUBA", "CHICONI", "CHIRONGUI", "CHOUNGUI", "COCONI", "COMBANI", "DAPANI", "DEMBéNI", "DZAOUDZI", "DZOUMOGNE", "HAGNOUNDROU", "HAMJAGO", "HAMOURO", "HANDREMA", "ILONI", "KAHANI", "KANGANI", "KANI-KéLI", "KANIBé", "KAVANI", "KAWéNI", "KOUNGOU", "LABATTOIR", "LONGONI", "MTSANGAMOUJI", "M\'TSANGAMOUJI", "M\'TSAMOUDOU", "MAJICAVO-KOROPA", "MAJICAVO-LAMIR", "MALAMANI", "MAMOUDZOU", "MANJAGOU", "MBOUANATSA", "MBOUINI", "MIRéRéNI", "MLIHA", "MOINATRINDI", "MRAMADOUDOU", "MRONABéJA", "MROUALé", "MTSAHARA", "MTSAMBORO", "MTSAMOUDOU", "MTSANGAMBOUA", "MTSAPéRé", "MZOUAZIA", "NYAMBADAO", "ONGOJOU", "OUANGANI", "PAMANDZI", "PASSAMAINTY", "PASSY-KéLI", "POROANI", "SADA", "SOHOA", "TRéVANI", "TSARARANO", "TSIMKOURA", "TSINGONI", "TSOUNDZOU 1", "TSOUNDZOU 2", "VAHIBé"], placeholder: "Entrer votre ville" %>
                    </label>
                    <label>Code postal *
                        <%= text_input f, :codepostal, value: @user.codepostal %>
                    </label>
                    
                </div>
                <div id="btn">
                    <button type="submit" class="btn">Sauvegarder l'adresse</button>
                </div>
            <% end %>
        </div>
</div>

lib/bebemayotte_web/templates/compte/voir.html.eex
<div class="product">
    <div class="voir">   
        <p>La commande n°27989835 a été passée le 4 mai 2021 et est actuellement Attente paiement.</p>
        <h2>Détails de la commande</h2> 
        <table class="tablevoir" >
            <thead>
                <tr>
                    <th class="com">PRODUITS</th>
                    <th class="com">TOTAL</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="commande">détail de l'article</td>
                    <td class="commande">prix</td>
                </tr>
                <tr>
                    <th >SOUS TOTAL:</th>
                    <td class="commande">prix</td>
                </tr>
                <tr>
                    <th >REMISE:</th>
                    <td class="commande">prix</td>
                </tr>
                <tr>
                    <th>EXPÉDITION:</th>
                    <th>Récupérer en boutique ( 0€ de frais).
                        Vous allez être contacté par l'équipe Web pour organiser 
                        l'enlèvement de votre commande.
                    </th>
                </tr>
                 <tr>
                    <th>MOYEN DE PAIEMENT :</th>
                    <th>E-Transactions payment</th>
                </tr>
                <tr>
                    <th>TOTAL :</th>
                    <th>prix</th>
                </tr>
            </tbody>
        </table>
        <h2>Adresse de facturation</h2> 
        <div class="facture">
            <h4>Nom+ prénom</h4>
            <h4>Rue du quartier</h4>
            <h4>Ville </h4>
            <i class="material-icons">&#xe0cd;</i><h4 id="icon">numero</h4>
          <i class="material-icons">mail_outline</i><h4 id="icon">e_mail</h4>
        </div>
    </div>
</div>